server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_tracker
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

application:
  security:
    jwt:
      secret-key: e56bca631be7b6d49050b643d601956836d8768cc9717232d4c217d1a84860e0
      expiration: 604800000 # 7 days